### ISSUE TITLE
API server panic due to http handler timeout

### ISSUE THREAD

**Issue by ankilosaurus** [kubernetes/apiserver#54]
Observed multiple panics in k8s apiserver as well as kube metric server version v0.3.1. Metrics server apis stop responding to hpa after this.

Below are traces from k8s api server logs 

```
/workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2065
/usr/local/go/src/runtime/asm_amd64.s:2361
E0626 00:13:15.271956       1 wrap.go:32] apiserver panic'd on GET /apis/metrics.k8s.io/v1beta1/nodes
I0626 00:13:15.272052       1 log.go:172] http2: panic serving 10.218.178.248:46060: killing connection/stream because serving request timed out and response had been started
goroutine 386036669 [running]:
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc7b9b18908, 0xc4bf1bffaf, 0xc654e7b880)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2058 +0x190
panic(0x47345e0, 0xc420235060)
    /usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc4bf1bfce8, 0x1, 0x1)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x47345e0, 0xc420235060)
    /usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc845415ee0, 0xc7140f3560)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:234 +0x190
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc439aedaa0, 0x6a5df80, 0xc839457a40, 0xc7a9d4d900)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:118 +0x2c1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x6a5df80, 0xc839457a40, 0xc7a9d4d800)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc423372ea0, 0x6a5df80, 0xc839457a40, 0xc7a9d4d800)
    /usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x6a5df80, 0xc839457a40, 0xc79b873000)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x181
net/http.HandlerFunc.ServeHTTP(0xc423372ed0, 0x6a5df80, 0xc839457a40, 0xc79b873000)
    /usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x6a5df80, 0xc839457a40, 0xc79b873000)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc439aedac0, 0x6a530c0, 0xc7b9b18908, 0xc79b873000)
    /usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc423372f00, 0x6a530c0, 0xc7b9b18908, 0xc79b873000)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc42c68c270, 0x6a530c0, 0xc7b9b18908, 0xc79b873000)
    /usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.initNPNRequest.ServeHTTP(0xc8885a7c00, 0xc42c68c270, 0x6a530c0, 0xc7b9b18908, 0xc79b873000)
    /usr/local/go/src/net/http/server.go:3263 +0x9a
net/http.(Handler).ServeHTTP-fm(0x6a530c0, 0xc7b9b18908, 0xc79b873000)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:241 +0x4d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc654e7b880, 0xc7b9b18908, 0xc79b873000, 0xc839d5e9c0)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2065 +0x89
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1799 +0x46b
```
and
```
E0625 20:53:58.158321       1 wrap.go:32] apiserver panic'd on GET /api/v1/pods?limit=500&resourceVersion=0
I0625 20:53:58.158455       1 log.go:172] http2: panic serving 10.218.176.149:60430: killing connection/stream because serving request timed out and response had been started
goroutine 367905912 [running]:
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc607cbccd0, 0xc73d1abfaf, 0xc42a1101c0)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2058 +0x190
panic(0x47345e0, 0xc420235060)
    /usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc73d1abce8, 0x1, 0x1)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x47345e0, 0xc420235060)
    /usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc5af63d780, 0xc4c1eb4870)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:234 +0x190
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc439aedaa0, 0x6a5df80, 0xc4abc62fc0, 0xc4ad418500)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:118 +0x2c1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x6a5df80, 0xc4abc62fc0, 0xc4ad418400)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc423372ea0, 0x6a5df80, 0xc4abc62fc0, 0xc4ad418400)
    /usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x6a5df80, 0xc4abc62fc0, 0xc495f36500)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x181
net/http.HandlerFunc.ServeHTTP(0xc423372ed0, 0x6a5df80, 0xc4abc62fc0, 0xc495f36500)
    /usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x6a5df80, 0xc4abc62fc0, 0xc495f36500)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc439aedac0, 0x6a530c0, 0xc607cbccd0, 0xc495f36500)
    /usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc423372f00, 0x6a530c0, 0xc607cbccd0, 0xc495f36500)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc42c68c270, 0x6a530c0, 0xc607cbccd0, 0xc495f36500)
    /usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.initNPNRequest.ServeHTTP(0xc63fe6e380, 0xc42c68c270, 0x6a530c0, 0xc607cbccd0, 0xc495f36500)
    /usr/local/go/src/net/http/server.go:3263 +0x9a
net/http.(Handler).ServeHTTP-fm(0x6a530c0, 0xc607cbccd0, 0xc495f36500)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:241 +0x4d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc42a1101c0, 0xc607cbccd0, 0xc495f36500, 0xc5aac283a0)
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2065 +0x89
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
    /workspace/anago-v1.12.8-beta.0.57+a89f8c11a5f4f1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1799 +0x46b
```

Please let me know if any more information is needed.

**Comment by yuchengwu** [comment]
My kubernetes version is 1.9, and I encounter same panic, starting from line 8748 is the first panic log

```
   8748 Trace[6105384]: [75.334µs] [75.334µs] About to List from storage
   8749 Trace[6105384]: [5.427484ms] [5.35215ms] Listing from storage done
   8750 Trace[6105384]: [14.696485ms] [9.269001ms] Self-linking done
   8751 Trace[6105384]: [51.357908193s] [51.343211708s] Writing http response done (1481 items)
   8752 Trace[6105384]: [51.357918068s] [9.875µs] END
   8753 I0703 18:42:27.727021       1 asm_amd64.s:509] GET /api/v1/endpoints?limit=500&resourceVersion=0: (1m9.740803696s) 200 [[nginx-ingress-controller/v0.0.0 (linux/amd64) kubernetes/$Format] 172.18.28
   8753 .14:52610]
   8754 E0703 18:42:27.738905       1 runtime.go:66] Observed a panic: &errors.errorString{s:"kill connection/stream"} (kill connection/stream)
   8755 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
   8756 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
   8757 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
   8758 /usr/local/go/src/runtime/asm_amd64.s:509
   8759 /usr/local/go/src/runtime/panic.go:491
   8760 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:217
   8761 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101
   8762 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51
   8763 /usr/local/go/src/net/http/server.go:1918
   8764 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45
   8765 /usr/local/go/src/net/http/server.go:1918
   8766 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110
   8767 /usr/local/go/src/net/http/server.go:1918
   8768 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41
   8769 /usr/local/go/src/net/http/server.go:1918
   8770 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:199
   8771 /usr/local/go/src/net/http/server.go:2619
   8772 /usr/local/go/src/net/http/server.go:3164
   8773 <autogenerated>:1
   8774 /usr/local/go/src/net/http/h2_bundle.go:5462
   8775 /usr/local/go/src/net/http/h2_bundle.go:5747
   8776 /usr/local/go/src/runtime/asm_amd64.s:2337
   8777 E0703 18:42:27.739248       1 wrap.go:34] APIServer panic'd on GET /api/v1/endpoints?limit=500&resourceVersion=0: kill connection/stream
   8778 goroutine 1409 [running]:
   8779 runtime/debug.Stack(0xa91daa0, 0xc426b0c540, 0x4bc8c84)
   8780         /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
   8781 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1.1(0x40c1c60, 0xc4202182d0)
   8782         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:34 +0x74
   8783 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc435ca1cf0, 0x1, 0x1)
   8784         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0xc8
   8785 panic(0x40c1c60, 0xc4202182d0)
   8786         /usr/local/go/src/runtime/panic.go:491 +0x283
   8787 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc42dbb0e00, 0xc4303a6090)
   8788         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:217 +0x190
   8789 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc429cff800, 0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8790         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101 +0x292
   8791 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8792         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51 +0xeb
   8793 net/http.HandlerFunc.ServeHTTP(0xc429884cc0, 0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8794         /usr/local/go/src/net/http/server.go:1918 +0x44
   8795 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8796         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x20f
   8797 net/http.HandlerFunc.ServeHTTP(0xc429884d00, 0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8798         /usr/local/go/src/net/http/server.go:1918 +0x44
   8799 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8800         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
   8801 net/http.HandlerFunc.ServeHTTP(0xc429cff820, 0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8802         /usr/local/go/src/net/http/server.go:1918 +0x44
   8803 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8804         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x108
   8805 net/http.HandlerFunc.ServeHTTP(0xc429cff840, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8806         /usr/local/go/src/net/http/server.go:1918 +0x44
   8807 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc422ed2600, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8808         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:199 +0x51
   8809 net/http.serverHandler.ServeHTTP(0xc42bc2d930, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8810         /usr/local/go/src/net/http/server.go:2619 +0xb4
   8811 net/http.initNPNRequest.ServeHTTP(0xc42b60e380, 0xc42bc2d930, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8812         /usr/local/go/src/net/http/server.go:3164 +0x9a
   8813 net/http.(*initNPNRequest).ServeHTTP(0xc42b471220, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8814         <autogenerated>:1 +0x63
   8815 net/http.(Handler).ServeHTTP-fm(0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8816         /usr/local/go/src/net/http/h2_bundle.go:5462 +0x4d
   8817 net/http.(*http2serverConn).runHandler(0xc4308a8c40, 0xc43162a040, 0xc4316a6500, 0xc42dbb0d80)
   8818         /usr/local/go/src/net/http/h2_bundle.go:5747 +0x89
   8819 created by net/http.(*http2serverConn).processHeaders
   8820         /usr/local/go/src/net/http/h2_bundle.go:5481 +0x495
   8821 
   8822 I0703 18:42:27.739407       1 logs.go:41] http2: panic serving 172.18.28.14:52610: kill connection/stream
   8823 goroutine 1409 [running]:
   8824 net/http.(*http2serverConn).runHandler.func1(0xc43162a040, 0xc435ca1faf, 0xc4308a8c40)
   8825         /usr/local/go/src/net/http/h2_bundle.go:5740 +0x190
   8826 panic(0x40c1c60, 0xc4202182d0)
   8827         /usr/local/go/src/runtime/panic.go:491 +0x283
   8828 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc435ca1cf0, 0x1, 0x1)
   8829         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
   8830 panic(0x40c1c60, 0xc4202182d0)
   8831         /usr/local/go/src/runtime/panic.go:491 +0x283
   8832 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc42dbb0e00, 0xc4303a6090)
   8833         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:217 +0x190
   8834 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc429cff800, 0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8835         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101 +0x292
   8836 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8837         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51 +0xeb
   8838 net/http.HandlerFunc.ServeHTTP(0xc429884cc0, 0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8839         /usr/local/go/src/net/http/server.go:1918 +0x44
   8840 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8841         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x20f
   8842 net/http.HandlerFunc.ServeHTTP(0xc429884d00, 0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8843         /usr/local/go/src/net/http/server.go:1918 +0x44
   8844 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8845         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
   8846 net/http.HandlerFunc.ServeHTTP(0xc429cff820, 0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8847         /usr/local/go/src/net/http/server.go:1918 +0x44
   8848 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0xa91daa0, 0xc426b0c540, 0xc4316a6500)
   8849         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x108
   8850 net/http.HandlerFunc.ServeHTTP(0xc429cff840, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8851         /usr/local/go/src/net/http/server.go:1918 +0x44
   8852 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc422ed2600, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8853         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:199 +0x51
   8854 net/http.serverHandler.ServeHTTP(0xc42bc2d930, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8855         /usr/local/go/src/net/http/server.go:2619 +0xb4
   8856 net/http.initNPNRequest.ServeHTTP(0xc42b60e380, 0xc42bc2d930, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8857         /usr/local/go/src/net/http/server.go:3164 +0x9a
   8858 net/http.(*initNPNRequest).ServeHTTP(0xc42b471220, 0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8859         <autogenerated>:1 +0x63
   8860 net/http.(Handler).ServeHTTP-fm(0xa91ef20, 0xc43162a040, 0xc4316a6500)
   8861         /usr/local/go/src/net/http/h2_bundle.go:5462 +0x4d
   8862 net/http.(*http2serverConn).runHandler(0xc4308a8c40, 0xc43162a040, 0xc4316a6500, 0xc42dbb0d80)
   8863         /usr/local/go/src/net/http/h2_bundle.go:5747 +0x89
   8864 created by net/http.(*http2serverConn).processHeaders
   8865         /usr/local/go/src/net/http/h2_bundle.go:5481 +0x495
   8866 I0703 18:42:27.746493       1 handler.go:161] kube-aggregator: GET "/apis/extensions/v1beta1/ingresses" satisfied by nonGoRestful

... ...
```
there are 3 apiserver running simultaneously in our cluster, but only one panics, the panic didn't last too long, after about 4 times, apiserver works normally.

**Comment by wgliang** [comment]
/reopen
/remove-lifecycle rotten

Facing the same issue.

**Comment by youngsoo777** [comment]
/reopen
/remove-lifecycle rotten

Facing the same issue...
